### ISSUE TITLE
'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' 제외

### ISSUE THREAD

**Issue by gofeel** [channel-io/channel-talk-ios-framework#5]
podspec의 
`'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64'`
설정은 Intel 기반 mac 시절 속도 향상을 위해 설정되던 설정으로 Apple slicon 기반의 개발기기가 주인 요즘에는 불필요한 부분입니다.
제거바랍니다.

제거 후에는 https://developers.channel.io/docs/troubleshooting에 대한 수정도 필요해 보입니다.

**Comment by bonoogi** [comment]
안녕하세요 @gofeel 님! 저는 채널톡 제품팀의 핀이라고 합니다. 우선 해당 이슈 제보해주셔서 감사드립니다.

말씀해주신 podspec 안의 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' 는 arm64 아키텍처 기반의 시뮬레이터가 없는 intel 기반 mac에서 빌드가 되지 않는 문제로 인해 부득이하게 적용된 설정입니다. 최근 Apple silicon 기반 mac이 많이 정착되긴 하였으나, 간혹 intel 기반 mac 환경에서 개발을 진행하시는 분도 계시다보니 해당 설정을 바로 삭제하기는 어려운 상황입니다. 대신 설정을 좀 더 간소화하거나 하는 방법을 팀 내부적으로 논의해보도록 하겠습니다! 더불어 언급해주신 개발자 문서의 내용도 함께 개선할 예정입니다.

만약 SDK 사용중에 설치가 안되거나 다른 문제가 발생하면 채널톡으로 문의주세요! 더 빠른 팔로업을 받으실 수 있습니다.

**Comment by gofeel** [comment]
일단, 속도 향상을 위한 부분이라고 생각했던건 다른 부분이었네요. 

해당 문제를 해결하는 방법은 다양(각 Podfile에서 덮어쓰기, Project의 architecture 설정으로 해결, 등등)하므로 관련 설정은 이 Pod를 사용하는 Project에서 결정해서 적용해야 할 문제입니다. 해당 문제가 없는 Project에서 관련 설정 강제하는 해결법으로 오히려 문제가 생기고 있습니다.

또, 이미 다른 Pod를 사용하는데 있어서도 관련 문제가 있고, 각각의 Project는 이 Pod 이와 관련된 설정을 적용하고 있을 것이라고 생각됩니다. 

관련 내용과 해결법을 알리는 것으로 충분하다고 생각합니다.

**Comment by bonoogi** [comment]
안녕하세요 @gofeel 님! 채널톡 제품팀의 핀입니다.

제보해주셨던 PodSpec 내 적용되고 있던 EXCLUDE_ARCHS 옵션이 제거된 버전이 배포되어 알려드려요. 현재 시점 기준으로 최신 버전(11.4.0)부터 PodSpec 내에 해당 옵션이 제거되어있습니다.

다시 한번 이슈 제보해주셔서 감사드립니다! 또 다른 문제가 있다면 언제든 채널톡으로 문의주세요.
