### ISSUE TITLE
readme 확인 불가

### ISSUE THREAD

**Issue by shinseunguk** [channel-io/channel-talk-ios-framework#6]
<img width="900" alt="image" src="https://github.com/channel-io/channel-talk-ios-framework/assets/69791286/262ac94b-7317-4f33-938d-fa9b1cdf38a1">

<img width="1432" alt="image" src="https://github.com/channel-io/channel-talk-ios-framework/assets/69791286/122443a1-185c-4691-9ad5-0e9fe5f47b6f">

**Comment by elesahich** [comment]
안녕하세요, 채널톡 제품팀 이안입니다. 제보해 주셔서 감사합니다.

링크는 수정되어 현재는 접근이 가능합니다. 혹시 다른 문의사항이 있으시다면 [채널톡](https://root.channel.io/home)으로 문의 주세요. 감사합니다.
